-- ######################################################################
-- #             SCRIPT DDL: SISTEMA HOTEL COCAO (V15.0)                #
-- ######################################################################
-- Sistema de gerenciamento de hotel com controle de reservas
-- Autor: Lucas Novais de Oliveira
-- Data: Outubro 2025
-- Parte 1/3: Tabelas com ajustes para CODIGO em todas as lookup tables
-- Notas:
-- - Compatível com MySQL / MariaDB
-- - Sistema projetado para um hotel pequeno e estudantil, evitando supercomplicações.
-- - Não usa tipos BOOLEAN, ARRAY ou OBJECTS para máxima compatibilidade.
-- - Não inclui HASH ou criptografia de senhas (fins didáticos).
-- - RG mantido simples, sem estados ou órgãos emissores.
-- - Índices são removíveis sem quebrar o sistema.
-- - Não há tabela de LOGGING, conforme especificado. No futuro pode ser adicionada se eu quiser, mas só se eu quiser.
-- - Triggers e constraints garantem integridade para um hotel pequeno.
-- ######################################################################

-- ======================================================================
-- 0. LIMPEZA DE OBJETOS ANTERIORES (Ordem Inversa à Criação)
-- ======================================================================
DROP TABLE IF EXISTS COCAO_HOSPEDE_SERVICO;
DROP TABLE IF EXISTS COCAO_SERVICO;
DROP TABLE IF EXISTS COCAO_RESERVA;
DROP TABLE IF EXISTS COCAO_STATUS_RESERVA;
DROP TABLE IF EXISTS COCAO_QUARTO;
DROP TABLE IF EXISTS COCAO_TIPO_QUARTO;
DROP TABLE IF EXISTS COCAO_FUNCIONARIO;
DROP TABLE IF EXISTS COCAO_FUNCAO;
DROP TABLE IF EXISTS COCAO_HOSPEDE;

-- ======================================================================
-- 1. COCAO_HOSPEDE (Superclasse - Generalização)
-- ======================================================================
CREATE TABLE COCAO_HOSPEDE (
    ID_USUARIO INT AUTO_INCREMENT,
    NOME_HOSPEDE VARCHAR(100) NOT NULL,
    CPF CHAR(11) NOT NULL,
    RG VARCHAR(20),
    SEXO CHAR(1) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    EMAIL VARCHAR(100),
    TELEFONE VARCHAR(20),
    TIPO INT DEFAULT 0 NOT NULL,
    ATIVO INT DEFAULT 1,

    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- PRIMARY KEY
    CONSTRAINT PK_COCAO_HOSPEDE PRIMARY KEY (ID_USUARIO),
    -- UNIQUE
    CONSTRAINT UK_COCAO_HOSPEDE_CPF     UNIQUE (CPF),
    -- CHECK
    CONSTRAINT CHK_COCAO_HOSPEDE_SEXO   CHECK (SEXO IN ('M','F','O')),
    CONSTRAINT CHK_COCAO_HOSPEDE_TIPO   CHECK (TIPO IN (0, 1)),
    CONSTRAINT CHK_COCAO_HOSPEDE_ATIVO  CHECK (ATIVO IN (1, 0)),
    -- CHECK COM REGEX PARA MYSQL
    CONSTRAINT CHK_COCAO_HOSPEDE_CPF    CHECK (CPF REGEXP '^[0-9]{11}$'),
    CONSTRAINT CHK_COCAO_HOSPEDE_EMAIL  CHECK (EMAIL IS NULL OR EMAIL REGEXP '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT CHK_COCAO_HOSPEDE_TEL    CHECK (TELEFONE IS NULL OR TELEFONE REGEXP '^[0-9\\s\\-\\(\\)]+$'),
    CONSTRAINT CHK_COCAO_HOSPEDE_RG     CHECK (RG IS NULL OR RG REGEXP '^[0-9A-Za-z\\-]{7,9}$')
);

-- ======================================================================
-- 2. COCAO_FUNCAO - LOOKUP TABLE
-- ======================================================================
CREATE TABLE COCAO_FUNCAO (
    CODIGO_FUNCAO   INT, -- Chave primária
    NOME_FUNCAO     VARCHAR(60) NOT NULL,
    DESCRICAO       VARCHAR(200),
    NIVEL_ACESSO    INT NOT NULL,
    CREATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT      DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- PRIMARY KEY
    CONSTRAINT PK_COCAO_FUNCAO PRIMARY KEY (CODIGO_FUNCAO),
    -- UNIQUE
    CONSTRAINT UK_COCAO_FUNCAO_NOME UNIQUE (NOME_FUNCAO),
    -- CHECK
    CONSTRAINT CHK_COCAO_FUNCAO_NIVEL CHECK (NIVEL_ACESSO BETWEEN 1 AND 3)
);

-- ======================================================================
-- 3. COCAO_FUNCIONARIO (Subclasse - Especialização de HOSPEDE)
-- ======================================================================
CREATE TABLE COCAO_FUNCIONARIO (
    ID_USUARIO INT,     -- FK, Referência a COCAO_HOSPEDE
    CODIGO_FUNCAO INT,       -- FK, Referência a COCAO_FUNCAO
    NOME_LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,  -- Sem criptografia para fins didáticos
    DATA_CONTRATACAO DATE NOT NULL,
    ATIVO INT DEFAULT 1 NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- PRIMARY KEY
    CONSTRAINT PK_COCAO_FUNCIONARIO PRIMARY KEY (ID_USUARIO),
    -- FOREIGN KEY
    CONSTRAINT FK_COCAO_FUNCIONARIO_HOSPEDE FOREIGN KEY (ID_USUARIO)
        REFERENCES COCAO_HOSPEDE(ID_USUARIO),
    CONSTRAINT FK_COCAO_FUNCIONARIO_CODIGO_FUNCAO FOREIGN KEY (CODIGO_FUNCAO)
        REFERENCES COCAO_FUNCAO(CODIGO_FUNCAO),
    -- UNIQUE
    CONSTRAINT UK_COCAO_FUNCIONARIO_LOGIN UNIQUE (NOME_LOGIN),
    -- CHECK
    CONSTRAINT CHK_COCAO_FUNCIONARIO_ATIVO CHECK (ATIVO IN (1, 0))
);

-- ======================================================================
-- 4. COCAO_TIPO_QUARTO - LOOKUP TABLE (Catálogo de Tipos de Quarto)
-- ======================================================================
CREATE TABLE COCAO_TIPO_QUARTO (
    CODIGO_TIPO_QUARTO INT NOT NULL,
    NOME_TIPO VARCHAR(50) NOT NULL, 
    CAPACIDADE_MAXIMA INT DEFAULT 2 NOT NULL,
    VALOR_DIARIA DECIMAL(10,2) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- PRIMARY KEY
    CONSTRAINT PK_COCAO_TIPO_QUARTO PRIMARY KEY (CODIGO_TIPO_QUARTO),
    -- UNIQUE
    CONSTRAINT UK_COCAO_TIPO_QUARTO_NOME UNIQUE (NOME_TIPO),
    -- CHECK
    CONSTRAINT CHK_COCAO_TIPO_CAPACIDADE CHECK (CAPACIDADE_MAXIMA > 0),
    CONSTRAINT CHK_COCAO_TIPO_VALOR CHECK (VALOR_DIARIA > 0)
);

-- ======================================================================
-- 5. COCAO_QUARTO (Catálogo de Quartos)
-- ======================================================================
CREATE TABLE COCAO_QUARTO (
    ID_QUARTO INT AUTO_INCREMENT,
    CODIGO_TIPO_QUARTO INT NOT NULL, -- FK, Referência a COCAO_TIPO_QUARTO
    NUMERO INT NOT NULL,
    STATUS_QUARTO VARCHAR(20) DEFAULT 'LIVRE',
    ANDAR INT DEFAULT 0 NOT NULL, -- novo campo ANDAR

    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- PRIMARY KEY
    CONSTRAINT PK_COCAO_QUARTO PRIMARY KEY (ID_QUARTO),
    -- FOREIGN KEY
    CONSTRAINT FK_COCAO_QUARTO_CODIGO_TIPO_QUARTO FOREIGN KEY (CODIGO_TIPO_QUARTO)
        REFERENCES COCAO_TIPO_QUARTO(CODIGO_TIPO_QUARTO),
    -- UNIQUE
    CONSTRAINT UK_COCAO_QUARTO_NUMERO UNIQUE (NUMERO),
    -- CHECK
    CONSTRAINT CHK_COCAO_QUARTO_STATUS CHECK (STATUS_QUARTO IN ('LIVRE','OCUPADO','MANUTENCAO')),
    CONSTRAINT CHK_COCAO_QUARTO_NUMERO CHECK (NUMERO >= 1),
    CONSTRAINT CHK_COCAO_QUARTO_ANDAR CHECK (ANDAR BETWEEN 0 AND 5)
);

-- ======================================================================
-- 6. COCAO_STATUS_RESERVA - LOOKUP TABLE (Tabela de Domínio)
-- ======================================================================
CREATE TABLE COCAO_STATUS_RESERVA (
    CODIGO_STATUS INT NOT NULL,
    DESCRICAO VARCHAR(20) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- PRIMARY KEY
    CONSTRAINT PK_COCAO_STATUS_RESERVA PRIMARY KEY (CODIGO_STATUS),
    -- UNIQUE
    CONSTRAINT UK_COCAO_STATUS_DESCRICAO UNIQUE (DESCRICAO)
);

-- ======================================================================
-- 7. COCAO_RESERVA (Transacional - Núcleo do Sistema)
-- ======================================================================
CREATE TABLE COCAO_RESERVA (
    ID_RESERVA INT AUTO_INCREMENT,
    CODIGO_STATUS INT DEFAULT 1 NOT NULL,     -- FK, Referência a COCAO_STATUS_RESERVA
    ID_USUARIO INT NOT NULL,                    -- FK, Referência a COCAO_HOSPEDE
    ID_QUARTO INT NOT NULL,                     -- FK, Referência a COCAO_QUARTO
    DATA_CHECK_IN DATETIME NOT NULL,
    DATA_CHECK_OUT DATETIME NOT NULL,
    NUMERO_HOSPEDES INT DEFAULT 1 NOT NULL,
    VALOR_TOTAL DECIMAL(10,2),
    NUMERO_DIARIAS INT DEFAULT 0 NOT NULL,

    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- PRIMARY KEY
    CONSTRAINT PK_COCAO_RESERVA PRIMARY KEY (ID_RESERVA),
    -- FOREIGN KEY
    CONSTRAINT FK_COCAO_RESERVA_HOSPEDE FOREIGN KEY (ID_USUARIO)
        REFERENCES COCAO_HOSPEDE(ID_USUARIO),
    CONSTRAINT FK_COCAO_RESERVA_QUARTO FOREIGN KEY (ID_QUARTO)
        REFERENCES COCAO_QUARTO(ID_QUARTO),
    CONSTRAINT FK_COCAO_RESERVA_CODIGO_STATUS FOREIGN KEY (CODIGO_STATUS)
        REFERENCES COCAO_STATUS_RESERVA(CODIGO_STATUS),
    -- CHECK
    CONSTRAINT CHK_COCAO_RESERVA_HOSPEDE CHECK (NUMERO_HOSPEDES <= 10),
    CONSTRAINT CHK_COCAO_RESERVA_VALOR CHECK (VALOR_TOTAL >= 0 OR VALOR_TOTAL IS NULL),
    CONSTRAINT CHK_COCAO_RESERVA_DATA1 CHECK (DATA_CHECK_OUT > DATA_CHECK_IN),
    CONSTRAINT CHK_COCAO_RESERVA_DIARIAS CHECK (NUMERO_DIARIAS >= 0)
);

-- ======================================================================
-- 8. COCAO_SERVICO - LOOKUP TABLE (Catálogo de Serviços Adicionais)
-- ======================================================================
CREATE TABLE COCAO_SERVICO (
    CODIGO_SERVICO INT NOT NULL,
    NOME_SERVICO VARCHAR(100) NOT NULL,
    PRECO DECIMAL(10,2) NOT NULL,
    ATIVO INT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- PRIMARY KEY
    CONSTRAINT PK_COCAO_SERVICO PRIMARY KEY (CODIGO_SERVICO),
    -- UNIQUE
    CONSTRAINT UK_COCAO_SERVICO_NOME UNIQUE (NOME_SERVICO),
    -- CHECK
    CONSTRAINT CHK_COCAO_SERVICO_PRECO CHECK (PRECO >= 0),
    CONSTRAINT CHK_COCAO_SERVICO_ATIVO CHECK (ATIVO IN (1, 0))
);

-- ======================================================================
-- 9. COCAO_HOSPEDE_SERVICO (Transacional - Solicitação de Serviços)
-- ======================================================================
CREATE TABLE COCAO_HOSPEDE_SERVICO (
    ID_SOLICITACAO      INT AUTO_INCREMENT,
    ID_USUARIO          INT NOT NULL,       -- FK, Referência a COCAO_HOSPEDE
    CODIGO_SERVICO      INT NOT NULL,     -- FK, Referência a COCAO_SERVICO
    ID_RESERVA          INT NOT NULL,       -- FK, Referência a COCAO_RESERVA (NOVO)
    DATA_SOLICITACAO    DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    QUANTIDADE          INT DEFAULT 1,

    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
    -- PRIMARY KEY
    CONSTRAINT PK_COCAO_HS_SOLICITACAO PRIMARY KEY (ID_SOLICITACAO),
    -- FOREIGN KEY
    CONSTRAINT FK_COCAO_HS_HOSPEDE FOREIGN KEY (ID_USUARIO)
        REFERENCES COCAO_HOSPEDE(ID_USUARIO),
    CONSTRAINT FK_COCAO_HS_CODIGO_SERVICO FOREIGN KEY (CODIGO_SERVICO)
        REFERENCES COCAO_SERVICO(CODIGO_SERVICO),
    CONSTRAINT FK_COCAO_HS_ID_RESERVA FOREIGN KEY (ID_RESERVA)
        REFERENCES COCAO_RESERVA(ID_RESERVA),
    -- CHECK
    CONSTRAINT CHK_COCAO_HS_QUANTIDADE CHECK (QUANTIDADE <= 100)
);

-- ======================================================================
-- LIMPEZA E CRIAÇÃO DE ÍNDICES, VIEWS E PROCEDURES
-- ======================================================================

-- O MySQL exige que não existam índices ao invés de usar DROP INDEX genérico
-- Como as tabelas foram dropadas, os índices foram junto. Apenas recriando:
CREATE INDEX COCAO_HOTEL_07_IDX_STATUS_QUARTO_RESERVA ON COCAO_RESERVA (ID_QUARTO, CODIGO_STATUS, DATA_CHECK_IN, DATA_CHECK_OUT);
CREATE INDEX COCAO_HOTEL_09_IDX_HOSPEDE_SERVICO ON COCAO_HOSPEDE_SERVICO (ID_USUARIO, CODIGO_SERVICO, DATA_SOLICITACAO);

DROP VIEW IF EXISTS COCAO_HOTEL_VIEW_01_STATUS_QUARTO;

CREATE VIEW COCAO_HOTEL_VIEW_01_STATUS_QUARTO AS
SELECT 
    q.ID_QUARTO,
    CASE 
        WHEN q.STATUS_QUARTO = 'MANUTENCAO' THEN 'MANUTENCAO'
        WHEN EXISTS (
            SELECT 1
            FROM COCAO_RESERVA r
            JOIN COCAO_STATUS_RESERVA sr ON r.CODIGO_STATUS = sr.CODIGO_STATUS
            WHERE r.ID_QUARTO = q.ID_QUARTO
              AND sr.DESCRICAO IN ('ABERTA', 'ATIVA')
              AND DATE(r.DATA_CHECK_OUT) > CURDATE()
              AND DATE(r.DATA_CHECK_IN) <= CURDATE()
        ) THEN 'OCUPADO'
        ELSE 'LIVRE'
    END AS STATUS_QUARTO,
    CURDATE() AS DATA_INICIO,
    CURDATE() AS DATA_FIM
FROM COCAO_QUARTO q;

-- ======================================================================
-- COCAO_HOTEL_SP_STATUS_QUARTO - Transformada em PROCEDURE para MySQL
-- ======================================================================
DROP PROCEDURE IF EXISTS COCAO_HOTEL_SP_STATUS_QUARTO;

DELIMITER //

CREATE PROCEDURE COCAO_HOTEL_SP_STATUS_QUARTO (
    IN p_data_inicio DATE,
    IN p_data_fim    DATE
)
BEGIN
    IF p_data_inicio IS NOT NULL AND p_data_fim IS NOT NULL AND p_data_inicio > p_data_fim THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20099] COCAO_HOTEL_SF_STATUS_QUARTO: Período inválido.';
    END IF;

    SELECT 
        q.ID_QUARTO,
        CASE 
            WHEN q.STATUS_QUARTO = 'MANUTENCAO' THEN 'MANUTENCAO'
            WHEN EXISTS (
                SELECT 1
                FROM COCAO_RESERVA r
                JOIN COCAO_STATUS_RESERVA sr ON r.CODIGO_STATUS = sr.CODIGO_STATUS
                WHERE r.ID_QUARTO = q.ID_QUARTO
                  AND sr.DESCRICAO IN ('ABERTA', 'ATIVA')
                  AND DATE(r.DATA_CHECK_OUT) > IFNULL(DATE(p_data_inicio), CURDATE())
                  AND DATE(r.DATA_CHECK_IN) <= IFNULL(DATE(p_data_fim), CURDATE())
            ) THEN 'OCUPADO'
            ELSE 'LIVRE'
        END AS STATUS_QUARTO,
        IFNULL(DATE(p_data_inicio), CURDATE()) AS DATA_INICIO,
        IFNULL(DATE(p_data_fim), CURDATE()) AS DATA_FIM
    FROM COCAO_QUARTO q;
END //

-- ######################################################################
-- #           TRIGGERS DE AUDITORIA - PARTE 2/3 - (T01 a T09)          #
-- ######################################################################
-- Convertido para arquitetura MySQL (Separação INSERT e UPDATE obrigatoriamente)

-- T01: COCAO_HOSPEDE
CREATE TRIGGER COCAO_HOTEL_01_TRG_AUD_HOSPEDE_INS
BEFORE INSERT ON COCAO_HOSPEDE FOR EACH ROW
BEGIN
    SET NEW.CREATED_AT = CURRENT_TIMESTAMP;
    SET NEW.UPDATED_AT = CURRENT_TIMESTAMP;
END //

CREATE TRIGGER COCAO_HOTEL_01_TRG_AUD_HOSPEDE_UPD
BEFORE UPDATE ON COCAO_HOSPEDE FOR EACH ROW
BEGIN
    IF NEW.TIPO = OLD.TIPO THEN
        SET NEW.UPDATED_AT = CURRENT_TIMESTAMP;
    END IF;
    SET NEW.CREATED_AT = OLD.CREATED_AT;
END //

-- T02: COCAO_FUNCAO
CREATE TRIGGER COCAO_HOTEL_02_TRG_AUD_FUNCAO_INS
BEFORE INSERT ON COCAO_FUNCAO FOR EACH ROW
BEGIN
    SET NEW.CREATED_AT = CURRENT_TIMESTAMP;
    SET NEW.UPDATED_AT = CURRENT_TIMESTAMP;
END //

CREATE TRIGGER COCAO_HOTEL_02_TRG_AUD_FUNCAO_UPD
BEFORE UPDATE ON COCAO_FUNCAO FOR EACH ROW
BEGIN
    SET NEW.CREATED_AT = OLD.CREATED_AT;
    SET NEW.UPDATED_AT = CURRENT_TIMESTAMP;
END //

-- T03: COCAO_FUNCIONARIO
CREATE TRIGGER COCAO_HOTEL_03_TRG_AUD_FUNC_INS
BEFORE INSERT ON COCAO_FUNCIONARIO FOR EACH ROW
BEGIN
    SET NEW.CREATED_AT = CURRENT_TIMESTAMP;
    SET NEW.UPDATED_AT = CURRENT_TIMESTAMP;
END //

CREATE TRIGGER COCAO_HOTEL_03_TRG_AUD_FUNC_UPD
BEFORE UPDATE ON COCAO_FUNCIONARIO FOR EACH ROW
BEGIN
    IF NEW.ATIVO = OLD.ATIVO THEN -- Ajuste generico, ja que funcionario não atualiza tipo
        SET NEW.UPDATED_AT = CURRENT_TIMESTAMP;
    END IF;
    SET NEW.CREATED_AT = OLD.CREATED_AT;
END //

-- T04: COCAO_TIPO_QUARTO
CREATE TRIGGER COCAO_HOTEL_04_TRG_AUD_TQUARTO_INS
BEFORE INSERT ON COCAO_TIPO_QUARTO FOR EACH ROW
BEGIN SET NEW.CREATED_AT = CURRENT_TIMESTAMP; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //

CREATE TRIGGER COCAO_HOTEL_04_TRG_AUD_TQUARTO_UPD
BEFORE UPDATE ON COCAO_TIPO_QUARTO FOR EACH ROW
BEGIN SET NEW.CREATED_AT = OLD.CREATED_AT; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //

-- T05: COCAO_QUARTO
CREATE TRIGGER COCAO_HOTEL_05_TRG_AUD_QUARTO_INS
BEFORE INSERT ON COCAO_QUARTO FOR EACH ROW
BEGIN SET NEW.CREATED_AT = CURRENT_TIMESTAMP; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //

CREATE TRIGGER COCAO_HOTEL_05_TRG_AUD_QUARTO_UPD
BEFORE UPDATE ON COCAO_QUARTO FOR EACH ROW
BEGIN SET NEW.CREATED_AT = OLD.CREATED_AT; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //

-- T06: COCAO_STATUS_RESERVA
CREATE TRIGGER COCAO_HOTEL_06_TRG_AUD_SRES_INS
BEFORE INSERT ON COCAO_STATUS_RESERVA FOR EACH ROW
BEGIN SET NEW.CREATED_AT = CURRENT_TIMESTAMP; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //

CREATE TRIGGER COCAO_HOTEL_06_TRG_AUD_SRES_UPD
BEFORE UPDATE ON COCAO_STATUS_RESERVA FOR EACH ROW
BEGIN SET NEW.CREATED_AT = OLD.CREATED_AT; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //

-- T07: COCAO_RESERVA
CREATE TRIGGER COCAO_HOTEL_07_TRG_AUD_RESERVA_INS
BEFORE INSERT ON COCAO_RESERVA FOR EACH ROW
BEGIN SET NEW.CREATED_AT = CURRENT_TIMESTAMP; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //

CREATE TRIGGER COCAO_HOTEL_07_TRG_AUD_RESERVA_UPD
BEFORE UPDATE ON COCAO_RESERVA FOR EACH ROW
BEGIN SET NEW.CREATED_AT = OLD.CREATED_AT; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //

-- T08: COCAO_SERVICO
CREATE TRIGGER COCAO_HOTEL_08_TRG_AUD_SERV_INS
BEFORE INSERT ON COCAO_SERVICO FOR EACH ROW
BEGIN SET NEW.CREATED_AT = CURRENT_TIMESTAMP; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //

CREATE TRIGGER COCAO_HOTEL_08_TRG_AUD_SERV_UPD
BEFORE UPDATE ON COCAO_SERVICO FOR EACH ROW
BEGIN SET NEW.CREATED_AT = OLD.CREATED_AT; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //

-- T09: COCAO_HOSPEDE_SERVICO
CREATE TRIGGER COCAO_HOTEL_09_TRG_AUD_HSERV_INS
BEFORE INSERT ON COCAO_HOSPEDE_SERVICO FOR EACH ROW
BEGIN SET NEW.CREATED_AT = CURRENT_TIMESTAMP; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //

CREATE TRIGGER COCAO_HOTEL_09_TRG_AUD_HSERV_UPD
BEFORE UPDATE ON COCAO_HOSPEDE_SERVICO FOR EACH ROW
BEGIN SET NEW.CREATED_AT = OLD.CREATED_AT; SET NEW.UPDATED_AT = CURRENT_TIMESTAMP; END //


-- ######################################################################
-- #               TRIGGERS DE INTEGRIDADE - PARTE 3/3                  #
-- ######################################################################

-- ======================================================================
-- T11: COCAO_HOSPEDE - Impede Exclusão com Reservas Ativas
-- ======================================================================
CREATE TRIGGER COCAO_HOTEL_11_TRG_HOSPEDE_DELETE
BEFORE DELETE ON COCAO_HOSPEDE
FOR EACH ROW
BEGIN
    DECLARE v_count_func INT;
    DECLARE v_count_res  INT;

    IF OLD.TIPO = 1 THEN
        SELECT COUNT(*) INTO v_count_func FROM COCAO_FUNCIONARIO WHERE ID_USUARIO = OLD.ID_USUARIO;
        IF v_count_func > 0 THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20020] COCAO_HOSPEDE/T11: Exclusão de funcionário bloqueada. Exclua primeiro o registro em COCAO_FUNCIONARIO.';
        END IF;
    END IF;

    SELECT COUNT(*) INTO v_count_res FROM COCAO_RESERVA
    WHERE ID_USUARIO = OLD.ID_USUARIO AND CODIGO_STATUS IN (1, 2, 3) AND CURDATE() < DATE(DATA_CHECK_OUT);

    IF v_count_res > 0 THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20021] COCAO_HOSPEDE/T11: Exclusão de hóspede bloqueada. Hóspede possui reservas ativas.';
    END IF;
END //

-- ======================================================================
-- T12: COCAO_QUARTO - Validação de Status em MANUTENCAO
-- ======================================================================
CREATE TRIGGER COCAO_HOTEL_12_TRG_STATUS_QUARTO
BEFORE UPDATE ON COCAO_QUARTO
FOR EACH ROW
BEGIN
    DECLARE v_count INT;
    
    IF NEW.STATUS_QUARTO = 'MANUTENCAO' THEN
        SELECT COUNT(*) INTO v_count FROM COCAO_RESERVA
        WHERE ID_QUARTO = NEW.ID_QUARTO AND CODIGO_STATUS IN (1, 2) AND DATE(DATA_CHECK_OUT) > CURDATE();
        
        IF v_count > 0 THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20030] COCAO_QUARTO/T12: Não é possível alterar quarto para MANUTENCAO. Quarto possui reservas ativas/abertas.';
        END IF;
    END IF;
END //

-- ======================================================================
-- T13: COCAO_RESERVA - Atualização de STATUS_QUARTO
-- ======================================================================
CREATE TRIGGER COCAO_HOTEL_13_TRG_RESERVA_STATUS_QUARTO_INS
AFTER INSERT ON COCAO_RESERVA
FOR EACH ROW
BEGIN
    DECLARE v_status_quarto VARCHAR(20);
    DECLARE v_count INT;

    SELECT STATUS_QUARTO INTO v_status_quarto FROM COCAO_QUARTO WHERE ID_QUARTO = NEW.ID_QUARTO;

    IF v_status_quarto != 'MANUTENCAO' THEN
        IF NEW.CODIGO_STATUS = 2 AND DATE(NEW.DATA_CHECK_OUT) > CURDATE() THEN
            SET v_count = 1;
        ELSE
            SET v_count = 0;
        END IF;

        UPDATE COCAO_QUARTO SET STATUS_QUARTO = CASE WHEN v_count > 0 THEN 'OCUPADO' ELSE 'LIVRE' END WHERE ID_QUARTO = NEW.ID_QUARTO;
    END IF;
END //

CREATE TRIGGER COCAO_HOTEL_13_TRG_RESERVA_STATUS_QUARTO_UPD
AFTER UPDATE ON COCAO_RESERVA
FOR EACH ROW
BEGIN
    DECLARE v_status_quarto VARCHAR(20);
    DECLARE v_count INT;

    SELECT STATUS_QUARTO INTO v_status_quarto FROM COCAO_QUARTO WHERE ID_QUARTO = NEW.ID_QUARTO;

    IF v_status_quarto != 'MANUTENCAO' THEN
        IF NEW.CODIGO_STATUS = 2 AND DATE(NEW.DATA_CHECK_OUT) > CURDATE() THEN
            SET v_count = 1;
        ELSE
            SET v_count = 0;
        END IF;

        UPDATE COCAO_QUARTO SET STATUS_QUARTO = CASE WHEN v_count > 0 THEN 'OCUPADO' ELSE 'LIVRE' END WHERE ID_QUARTO = NEW.ID_QUARTO;
    END IF;
END //

-- ======================================================================
-- T14: COCAO_RESERVA - Controle de Transição de Status
-- ======================================================================
CREATE TRIGGER COCAO_HOTEL_14_TRG_RESERVA_STATUS_TRANSICAO
BEFORE UPDATE ON COCAO_RESERVA
FOR EACH ROW
BEGIN
    IF OLD.CODIGO_STATUS != NEW.CODIGO_STATUS THEN
        CASE OLD.CODIGO_STATUS
            WHEN 1 THEN
                IF NEW.CODIGO_STATUS NOT IN (2, 3, 5) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20016] Transição de ABERTA inválida.'; END IF;
            WHEN 2 THEN
                IF NEW.CODIGO_STATUS NOT IN (3, 4) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20017] Transição de ATIVA inválida.'; END IF;
                IF NEW.CODIGO_STATUS = 4 AND DATE(OLD.DATA_CHECK_OUT) > CURDATE() THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20024] Finalização prematura.'; END IF;
            WHEN 3 THEN
                IF NEW.CODIGO_STATUS NOT IN (4, 5) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20018] Transição de A_PAGAR inválida.'; END IF;
                IF NEW.CODIGO_STATUS = 4 AND DATE(OLD.DATA_CHECK_OUT) > CURDATE() THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20024] Finalização prematura.'; END IF;
            WHEN 4 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20023] Reserva FINALIZADA.';
            WHEN 5 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20023] Reserva CANCELADA.';
            ELSE SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20012] Status inválido.';
        END CASE;
    END IF;
END //

-- ======================================================================
-- T15: COCAO_RESERVA - Validação de Conflitos e Capacidade
-- Convertido para validar BEFORE no MySQL (não precisa de compound)
-- ======================================================================
CREATE TRIGGER COCAO_HOTEL_15_TRG_RESERVA_CONFLITO_INS
BEFORE INSERT ON COCAO_RESERVA
FOR EACH ROW
BEGIN
    DECLARE v_status_quarto VARCHAR(20);
    DECLARE v_capacidade_maxima INT;
    DECLARE v_count_conflitos INT;

    IF NEW.NUMERO_HOSPEDES <= 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20025] Número de hóspedes inválido.'; END IF;
    
    SET NEW.DATA_CHECK_IN = DATE(NEW.DATA_CHECK_IN);
    SET NEW.DATA_CHECK_OUT = DATE(NEW.DATA_CHECK_OUT);
    SET NEW.NUMERO_DIARIAS = DATEDIFF(NEW.DATA_CHECK_OUT, NEW.DATA_CHECK_IN);
    
    SELECT STATUS_QUARTO, CAPACIDADE_MAXIMA INTO v_status_quarto, v_capacidade_maxima
    FROM COCAO_QUARTO q JOIN COCAO_TIPO_QUARTO qt ON q.CODIGO_TIPO_QUARTO = qt.CODIGO_TIPO_QUARTO WHERE q.ID_QUARTO = NEW.ID_QUARTO;
    
    IF v_status_quarto = 'MANUTENCAO' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20014] Quarto em manutenção.'; END IF;
    IF NEW.NUMERO_HOSPEDES > v_capacidade_maxima THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20015] Capacidade excedida.'; END IF;
    
    SELECT COUNT(*) INTO v_count_conflitos FROM COCAO_RESERVA r
    WHERE r.ID_QUARTO = NEW.ID_QUARTO AND r.CODIGO_STATUS IN (1, 2) AND r.ID_RESERVA != IFNULL(NEW.ID_RESERVA, -1)
      AND DATE(r.DATA_CHECK_OUT) > DATE(NEW.DATA_CHECK_IN) AND DATE(r.DATA_CHECK_IN) < DATE(NEW.DATA_CHECK_OUT);
    
    IF v_count_conflitos > 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20016] Conflito de reserva.'; END IF;
END //

CREATE TRIGGER COCAO_HOTEL_15_TRG_RESERVA_CONFLITO_UPD
BEFORE UPDATE ON COCAO_RESERVA
FOR EACH ROW
BEGIN
    DECLARE v_status_quarto VARCHAR(20);
    DECLARE v_capacidade_maxima INT;
    DECLARE v_count_conflitos INT;

    IF NEW.NUMERO_HOSPEDES <= 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20025] Número de hóspedes inválido.'; END IF;
    
    SET NEW.DATA_CHECK_IN = DATE(NEW.DATA_CHECK_IN);
    SET NEW.DATA_CHECK_OUT = DATE(NEW.DATA_CHECK_OUT);
    SET NEW.NUMERO_DIARIAS = DATEDIFF(NEW.DATA_CHECK_OUT, NEW.DATA_CHECK_IN);
    
    SELECT STATUS_QUARTO, CAPACIDADE_MAXIMA INTO v_status_quarto, v_capacidade_maxima
    FROM COCAO_QUARTO q JOIN COCAO_TIPO_QUARTO qt ON q.CODIGO_TIPO_QUARTO = qt.CODIGO_TIPO_QUARTO WHERE q.ID_QUARTO = NEW.ID_QUARTO;
    
    IF v_status_quarto = 'MANUTENCAO' THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20014] Quarto em manutenção.'; END IF;
    IF NEW.NUMERO_HOSPEDES > v_capacidade_maxima THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20015] Capacidade excedida.'; END IF;
    
    SELECT COUNT(*) INTO v_count_conflitos FROM COCAO_RESERVA r
    WHERE r.ID_QUARTO = NEW.ID_QUARTO AND r.CODIGO_STATUS IN (1, 2) AND r.ID_RESERVA != IFNULL(NEW.ID_RESERVA, -1)
      AND DATE(r.DATA_CHECK_OUT) > DATE(NEW.DATA_CHECK_IN) AND DATE(r.DATA_CHECK_IN) < DATE(NEW.DATA_CHECK_OUT);
    
    IF v_count_conflitos > 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20016] Conflito de reserva.'; END IF;
END //

-- ======================================================================
-- T16: COCAO_SERVICO - Atualiza VALOR_TOTAL de Reservas
-- ======================================================================
CREATE TRIGGER COCAO_HOTEL_16_TRG_ATUALIZA_SERVICO
AFTER UPDATE ON COCAO_SERVICO
FOR EACH ROW
BEGIN
    UPDATE COCAO_RESERVA r
    SET VALOR_TOTAL = (
        SELECT t.VALOR_DIARIA * r.NUMERO_DIARIAS
        FROM COCAO_QUARTO q JOIN COCAO_TIPO_QUARTO t ON q.CODIGO_TIPO_QUARTO = t.CODIGO_TIPO_QUARTO
        WHERE q.ID_QUARTO = r.ID_QUARTO
    ) + COALESCE((
        SELECT SUM(s.PRECO * hs.QUANTIDADE)
        FROM COCAO_HOSPEDE_SERVICO hs JOIN COCAO_SERVICO s ON hs.CODIGO_SERVICO = s.CODIGO_SERVICO
        WHERE hs.ID_RESERVA = r.ID_RESERVA
          AND DATE(hs.DATA_SOLICITACAO) >= DATE(r.DATA_CHECK_IN) AND DATE(hs.DATA_SOLICITACAO) < DATE(r.DATA_CHECK_OUT)
    ), 0)
    WHERE r.CODIGO_STATUS IN (1, 2)
      AND EXISTS (
          SELECT 1 FROM COCAO_HOSPEDE_SERVICO hs
          WHERE hs.ID_RESERVA = r.ID_RESERVA AND hs.CODIGO_SERVICO = NEW.CODIGO_SERVICO
            AND DATE(hs.DATA_SOLICITACAO) >= DATE(r.DATA_CHECK_IN) AND DATE(hs.DATA_SOLICITACAO) < DATE(r.DATA_CHECK_OUT)
      );
END //

-- ======================================================================
-- T17: COCAO_HOSPEDE_SERVICO - Atualiza VALOR_TOTAL da Reserva
-- ======================================================================
CREATE TRIGGER COCAO_HOTEL_17_TRG_ATUALIZA_RESERVA_INS
AFTER INSERT ON COCAO_HOSPEDE_SERVICO
FOR EACH ROW
BEGIN
    UPDATE COCAO_RESERVA r
    SET VALOR_TOTAL = (
        SELECT t.VALOR_DIARIA * r.NUMERO_DIARIAS FROM COCAO_QUARTO q JOIN COCAO_TIPO_QUARTO t ON q.CODIGO_TIPO_QUARTO = t.CODIGO_TIPO_QUARTO WHERE q.ID_QUARTO = r.ID_QUARTO
    ) + COALESCE((
        SELECT SUM(s.PRECO * hs.QUANTIDADE) FROM COCAO_HOSPEDE_SERVICO hs JOIN COCAO_SERVICO s ON hs.CODIGO_SERVICO = s.CODIGO_SERVICO
        WHERE hs.ID_RESERVA = r.ID_RESERVA AND DATE(hs.DATA_SOLICITACAO) >= DATE(r.DATA_CHECK_IN) AND DATE(hs.DATA_SOLICITACAO) < DATE(r.DATA_CHECK_OUT)
    ), 0)
    WHERE r.ID_RESERVA = NEW.ID_RESERVA AND r.CODIGO_STATUS IN (1, 2);
END //

CREATE TRIGGER COCAO_HOTEL_17_TRG_ATUALIZA_RESERVA_UPD
AFTER UPDATE ON COCAO_HOSPEDE_SERVICO
FOR EACH ROW
BEGIN
    UPDATE COCAO_RESERVA r
    SET VALOR_TOTAL = (
        SELECT t.VALOR_DIARIA * r.NUMERO_DIARIAS FROM COCAO_QUARTO q JOIN COCAO_TIPO_QUARTO t ON q.CODIGO_TIPO_QUARTO = t.CODIGO_TIPO_QUARTO WHERE q.ID_QUARTO = r.ID_QUARTO
    ) + COALESCE((
        SELECT SUM(s.PRECO * hs.QUANTIDADE) FROM COCAO_HOSPEDE_SERVICO hs JOIN COCAO_SERVICO s ON hs.CODIGO_SERVICO = s.CODIGO_SERVICO
        WHERE hs.ID_RESERVA = r.ID_RESERVA AND DATE(hs.DATA_SOLICITACAO) >= DATE(r.DATA_CHECK_IN) AND DATE(hs.DATA_SOLICITACAO) < DATE(r.DATA_CHECK_OUT)
    ), 0)
    WHERE r.ID_RESERVA = NEW.ID_RESERVA AND r.CODIGO_STATUS IN (1, 2);
END //

CREATE TRIGGER COCAO_HOTEL_17_TRG_ATUALIZA_RESERVA_DEL
AFTER DELETE ON COCAO_HOSPEDE_SERVICO
FOR EACH ROW
BEGIN
    UPDATE COCAO_RESERVA r
    SET VALOR_TOTAL = (
        SELECT t.VALOR_DIARIA * r.NUMERO_DIARIAS FROM COCAO_QUARTO q JOIN COCAO_TIPO_QUARTO t ON q.CODIGO_TIPO_QUARTO = t.CODIGO_TIPO_QUARTO WHERE q.ID_QUARTO = r.ID_QUARTO
    ) + COALESCE((
        SELECT SUM(s.PRECO * hs.QUANTIDADE) FROM COCAO_HOSPEDE_SERVICO hs JOIN COCAO_SERVICO s ON hs.CODIGO_SERVICO = s.CODIGO_SERVICO
        WHERE hs.ID_RESERVA = r.ID_RESERVA AND DATE(hs.DATA_SOLICITACAO) >= DATE(r.DATA_CHECK_IN) AND DATE(hs.DATA_SOLICITACAO) < DATE(r.DATA_CHECK_OUT)
    ), 0)
    WHERE r.ID_RESERVA = OLD.ID_RESERVA AND r.CODIGO_STATUS IN (1, 2);
END //

-- ======================================================================
-- T18: COCAO_HOSPEDE_SERVICO - Validação de Serviço Ativo
-- ======================================================================
CREATE TRIGGER COCAO_HOTEL_18_TRG_SERVICO_ATIVO_INS
BEFORE INSERT ON COCAO_HOSPEDE_SERVICO
FOR EACH ROW
BEGIN
    DECLARE v_ativo INT;
    DECLARE v_count INT;

    IF NEW.QUANTIDADE > 100 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20047] Quantidade excede o limite.'; END IF;
    
    SELECT ATIVO INTO v_ativo FROM COCAO_SERVICO WHERE CODIGO_SERVICO = NEW.CODIGO_SERVICO;
    IF v_ativo = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20045] Serviço inativo.'; END IF;
    
    SELECT COUNT(*) INTO v_count FROM COCAO_RESERVA r
    WHERE r.ID_RESERVA = NEW.ID_RESERVA AND r.CODIGO_STATUS IN (1, 2)
      AND DATE(NEW.DATA_SOLICITACAO) >= DATE(r.DATA_CHECK_IN) AND DATE(NEW.DATA_SOLICITACAO) < DATE(r.DATA_CHECK_OUT);
    
    IF v_count = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20046] Reserva inválida para a data solicitada.'; END IF;
END //

CREATE TRIGGER COCAO_HOTEL_18_TRG_SERVICO_ATIVO_UPD
BEFORE UPDATE ON COCAO_HOSPEDE_SERVICO
FOR EACH ROW
BEGIN
    DECLARE v_ativo INT;
    DECLARE v_count INT;

    IF NEW.QUANTIDADE > 100 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20047] Quantidade excede o limite.'; END IF;
    
    SELECT ATIVO INTO v_ativo FROM COCAO_SERVICO WHERE CODIGO_SERVICO = NEW.CODIGO_SERVICO;
    IF v_ativo = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20045] Serviço inativo.'; END IF;
    
    SELECT COUNT(*) INTO v_count FROM COCAO_RESERVA r
    WHERE r.ID_RESERVA = NEW.ID_RESERVA AND r.CODIGO_STATUS IN (1, 2)
      AND DATE(NEW.DATA_SOLICITACAO) >= DATE(r.DATA_CHECK_IN) AND DATE(NEW.DATA_SOLICITACAO) < DATE(r.DATA_CHECK_OUT);
    
    IF v_count = 0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = '[-20046] Reserva inválida para a data solicitada.'; END IF;
END //

-- ======================================================================
-- T19: COCAO_FUNCIONARIO - Atualização automática de TIPO=1 em COCAO_HOSPEDE
-- ======================================================================
CREATE TRIGGER COCAO_HOTEL_19_TRG_FUNCIONARIO_TIPO_INS
AFTER INSERT ON COCAO_FUNCIONARIO
FOR EACH ROW
BEGIN
    UPDATE COCAO_HOSPEDE SET TIPO = 1, UPDATED_AT = CURRENT_TIMESTAMP WHERE ID_USUARIO = NEW.ID_USUARIO;
END //

CREATE TRIGGER COCAO_HOTEL_19_TRG_FUNCIONARIO_TIPO_UPD
AFTER UPDATE ON COCAO_FUNCIONARIO
FOR EACH ROW
BEGIN
    UPDATE COCAO_HOSPEDE SET TIPO = 1, UPDATED_AT = CURRENT_TIMESTAMP WHERE ID_USUARIO = NEW.ID_USUARIO;
END //

-- ======================================================================
-- T20: COCAO_RESERVA - Recálculo de VALOR_TOTAL após Alterações Críticas
-- Reescrito para BEFORE UPDATE para não causar loop infinito em si mesma
-- ======================================================================
CREATE TRIGGER COCAO_HOTEL_20_TRG_RESERVA_VALOR_RECALCULADO_UPD
BEFORE UPDATE ON COCAO_RESERVA
FOR EACH ROW
BEGIN
    DECLARE v_valor_diaria DECIMAL(10,2);
    DECLARE v_soma_servicos DECIMAL(10,2);

    IF NEW.CODIGO_STATUS IN (1, 2) THEN
        SELECT t.VALOR_DIARIA INTO v_valor_diaria
        FROM COCAO_QUARTO q JOIN COCAO_TIPO_QUARTO t ON q.CODIGO_TIPO_QUARTO = t.CODIGO_TIPO_QUARTO
        WHERE q.ID_QUARTO = NEW.ID_QUARTO;

        SELECT COALESCE(SUM(s.PRECO * hs.QUANTIDADE), 0) INTO v_soma_servicos
        FROM COCAO_HOSPEDE_SERVICO hs JOIN COCAO_SERVICO s ON hs.CODIGO_SERVICO = s.CODIGO_SERVICO
        WHERE hs.ID_RESERVA = NEW.ID_RESERVA
          AND DATE(hs.DATA_SOLICITACAO) >= DATE(NEW.DATA_CHECK_IN)
          AND DATE(hs.DATA_SOLICITACAO) < DATE(NEW.DATA_CHECK_OUT);

        SET NEW.VALOR_TOTAL = (v_valor_diaria * NEW.NUMERO_DIARIAS) + v_soma_servicos;
    END IF;
END //

DELIMITER ;