
-- Obs: Oracle NÃO aceita múltiplas tuplas com VALUES (...), (...), (...)

-- Opção 1 — Fazer vários INSERTs separados, Exemplo:

-- INSERT INTO COCAO_FUNCAO (CODIGO_FUNCAO, NOME_FUNCAO, DESCRICAO, NIVEL_ACESSO)
-- VALUES (1001, 'Recepcionista', 'Atende hóspedes, faz check-in/check-out, gerencia reservas', 1);

-- INSERT INTO COCAO_FUNCAO (CODIGO_FUNCAO, NOME_FUNCAO, DESCRICAO, NIVEL_ACESSO)
-- VALUES (1002, 'Camareira', 'Limpeza e arrumação dos quartos', 1);
-- ...

-- Opção 2 — Usar INSERT ALL (mais eficiente para múltiplas linhas), como abaixo:

-- ======================================================================
-- SEED DATA: TODAS AS LOOKUP TABLES (ORACLE 21c COMPATÍVEL)
-- ======================================================================

-- COCAO_FUNCAO
INSERT ALL
    INTO COCAO_FUNCAO (CODIGO_FUNCAO, NOME_FUNCAO, DESCRICAO, NIVEL_ACESSO)
        VALUES (1001, 'Recepcionista', 'Atende hóspedes, faz check-in/check-out, gerencia reservas', 2)
    INTO COCAO_FUNCAO (CODIGO_FUNCAO, NOME_FUNCAO, DESCRICAO, NIVEL_ACESSO)
        VALUES (1002, 'Camareira', 'Limpeza e arrumação dos quartos', 2)
    INTO COCAO_FUNCAO (CODIGO_FUNCAO, NOME_FUNCAO, DESCRICAO, NIVEL_ACESSO)
        VALUES (2001, 'Gerente de Recepção', 'Supervisiona recepcionistas, resolve problemas de hóspedes', 2)
    INTO COCAO_FUNCAO (CODIGO_FUNCAO, NOME_FUNCAO, DESCRICAO, NIVEL_ACESSO)
        VALUES (2002, 'Supervisor de Limpeza', 'Gerencia equipe de camareiras, verifica quartos', 2)
    INTO COCAO_FUNCAO (CODIGO_FUNCAO, NOME_FUNCAO, DESCRICAO, NIVEL_ACESSO)
        VALUES (3001, 'Gerente Geral', 'Administra todo o hotel, acesso total ao sistema', 3)
    INTO COCAO_FUNCAO (CODIGO_FUNCAO, NOME_FUNCAO, DESCRICAO, NIVEL_ACESSO)
        VALUES (3002, 'Gerente de Manutenção', 'Responsável por reparos e manutenção dos quartos', 3)
SELECT * FROM DUAL;

-- COCAO_TIPO_QUARTO
INSERT ALL
    INTO COCAO_TIPO_QUARTO (CODIGO_TIPO_QUARTO, NOME_TIPO, CAPACIDADE_MAXIMA, VALOR_DIARIA)
        VALUES (1001, 'Solteiro', 1, 120.00)
    INTO COCAO_TIPO_QUARTO (CODIGO_TIPO_QUARTO, NOME_TIPO, CAPACIDADE_MAXIMA, VALOR_DIARIA)
        VALUES (1002, 'Casal Standard', 2, 180.00)
    INTO COCAO_TIPO_QUARTO (CODIGO_TIPO_QUARTO, NOME_TIPO, CAPACIDADE_MAXIMA, VALOR_DIARIA)
        VALUES (1003, 'Casal Superior', 2, 220.00)
    INTO COCAO_TIPO_QUARTO (CODIGO_TIPO_QUARTO, NOME_TIPO, CAPACIDADE_MAXIMA, VALOR_DIARIA)
        VALUES (1004, 'Família', 4, 320.00)
    INTO COCAO_TIPO_QUARTO (CODIGO_TIPO_QUARTO, NOME_TIPO, CAPACIDADE_MAXIMA, VALOR_DIARIA)
        VALUES (1005, 'Suíte Executiva', 2, 380.00)
    INTO COCAO_TIPO_QUARTO (CODIGO_TIPO_QUARTO, NOME_TIPO, CAPACIDADE_MAXIMA, VALOR_DIARIA)
        VALUES (1006, 'Suíte Master', 3, 520.00)
SELECT * FROM DUAL;

-- COCAO_STATUS_RESERVA
INSERT ALL
    INTO COCAO_STATUS_RESERVA (CODIGO_STATUS, DESCRICAO)
        VALUES (1, 'ABERTA')
    INTO COCAO_STATUS_RESERVA (CODIGO_STATUS, DESCRICAO)
        VALUES (2, 'ATIVA')
    INTO COCAO_STATUS_RESERVA (CODIGO_STATUS, DESCRICAO)
        VALUES (3, 'A_PAGAR')
    INTO COCAO_STATUS_RESERVA (CODIGO_STATUS, DESCRICAO)
        VALUES (4, 'FINALIZADA')
    INTO COCAO_STATUS_RESERVA (CODIGO_STATUS, DESCRICAO)
        VALUES (5, 'CANCELADA')
SELECT * FROM DUAL;

-- COCAO_SERVICO
INSERT ALL
    INTO COCAO_SERVICO (CODIGO_SERVICO, NOME_SERVICO, PRECO, ATIVO)
        VALUES (0101, 'Café da Manhã', 25.00, 1)
    INTO COCAO_SERVICO (CODIGO_SERVICO, NOME_SERVICO, PRECO, ATIVO)
        VALUES (0102, 'Almoço', 45.00, 1)
    INTO COCAO_SERVICO (CODIGO_SERVICO, NOME_SERVICO, PRECO, ATIVO)
        VALUES (0103, 'Jantar', 55.00, 1)
    INTO COCAO_SERVICO (CODIGO_SERVICO, NOME_SERVICO, PRECO, ATIVO)
        VALUES (0201, 'Lavanderia (por peça)', 10.00, 1)
    INTO COCAO_SERVICO (CODIGO_SERVICO, NOME_SERVICO, PRECO, ATIVO)
        VALUES (0202, 'Passadoria Rápida', 15.00, 1)
    INTO COCAO_SERVICO (CODIGO_SERVICO, NOME_SERVICO, PRECO, ATIVO)
        VALUES (0203, 'Limpeza Extra de Quarto', 40.00, 1)
    INTO COCAO_SERVICO (CODIGO_SERVICO, NOME_SERVICO, PRECO, ATIVO)
        VALUES (0301, 'Estacionamento (diária)', 30.00, 1)
    INTO COCAO_SERVICO (CODIGO_SERVICO, NOME_SERVICO, PRECO, ATIVO)
        VALUES (0302, 'Transfer Aeroporto → Hotel', 80.00, 1)
    INTO COCAO_SERVICO (CODIGO_SERVICO, NOME_SERVICO, PRECO, ATIVO)
        VALUES (0303, 'Transfer Hotel → Aeroporto', 80.00, 1)
    INTO COCAO_SERVICO (CODIGO_SERVICO, NOME_SERVICO, PRECO, ATIVO)
        VALUES (0404, 'Berço para Bebê', 35.00, 1)
    INTO COCAO_SERVICO (CODIGO_SERVICO, NOME_SERVICO, PRECO, ATIVO)
        VALUES (0405, 'Cama Extra', 50.00, 1)
SELECT * FROM DUAL;

COMMIT;

-- LIMPE TUDO ANTES (se quiser recomeçar)
DELETE FROM COCAO_HOSPEDE_SERVICO;
DELETE FROM COCAO_RESERVA;
DELETE FROM COCAO_QUARTO;
DELETE FROM COCAO_FUNCIONARIO;
DELETE FROM COCAO_HOSPEDE WHERE TIPO = 0 OR TIPO = 1;

-- ==============================================================
-- 2. HÓSPEDES (TIPO=0) — por CPF único
-- ==============================================================

INSERT INTO COCAO_HOSPEDE (NOME_HOSPEDE, CPF, RG, SEXO, DATA_NASCIMENTO, EMAIL, TELEFONE, TIPO)
VALUES ('Ana Silva', '11122233344', '1234567', 'F', DATE '1990-05-15', 'ana@email.com', '11987654321', 0);

INSERT INTO COCAO_HOSPEDE (NOME_HOSPEDE, CPF, RG, SEXO, DATA_NASCIMENTO, EMAIL, TELEFONE, TIPO)
VALUES ('Pedro Costa', '55566677788', '7654321', 'M', DATE '1985-08-22', 'pedro@email.com', '21998765432', 0);

INSERT INTO COCAO_HOSPEDE (NOME_HOSPEDE, CPF, RG, SEXO, DATA_NASCIMENTO, EMAIL, TELEFONE, TIPO)
VALUES ('Maria Oliveira', '99988877766', '1122334', 'F', DATE '1992-03-10', 'maria@email.com', '31997755443', 0);

-- ==============================================================
-- 3. FUNCIONÁRIOS (TIPO=1) + COCAO_FUNCIONARIO
-- ==============================================================

INSERT INTO COCAO_HOSPEDE (NOME_HOSPEDE, CPF, RG, SEXO, DATA_NASCIMENTO, EMAIL, TELEFONE, TIPO)
VALUES ('João Santos', '22233344455', '2233445', 'M', DATE '1988-07-12', 'joao@hotel.com', '11911112222', 1);

INSERT INTO COCAO_FUNCIONARIO (ID_USUARIO, CODIGO_FUNCAO, NOME_LOGIN, SENHA, DATA_CONTRATACAO, ATIVO)
SELECT h.ID_USUARIO, 1001, 'joao.recep', 'joao123', DATE '2023-01-15', 1
FROM COCAO_HOSPEDE h
WHERE h.CPF = '22233344455';

INSERT INTO COCAO_HOSPEDE (NOME_HOSPEDE, CPF, RG, SEXO, DATA_NASCIMENTO, EMAIL, TELEFONE, TIPO)
VALUES ('Carla Lima', '33344455566', '3344556', 'F', DATE '1995-11-30', 'carla@hotel.com', '11922223333', 1);

INSERT INTO COCAO_FUNCIONARIO (ID_USUARIO, CODIGO_FUNCAO, NOME_LOGIN, SENHA, DATA_CONTRATACAO, ATIVO)
SELECT h.ID_USUARIO, 1002, 'carla.camareira', 'carla123', DATE '2024-03-20', 1
FROM COCAO_HOSPEDE h
WHERE h.CPF = '33344455566';

-- ==============================================================
-- 4. QUARTOS — por NUMERO + ANDAR (único)
-- ==============================================================

INSERT INTO COCAO_QUARTO (CODIGO_TIPO_QUARTO, NUMERO, ANDAR, STATUS_QUARTO)
VALUES (1001, 101, 1, 'LIVRE');

INSERT INTO COCAO_QUARTO (CODIGO_TIPO_QUARTO, NUMERO, ANDAR, STATUS_QUARTO)
VALUES (1002, 201, 2, 'LIVRE');

INSERT INTO COCAO_QUARTO (CODIGO_TIPO_QUARTO, NUMERO, ANDAR, STATUS_QUARTO)
VALUES (1005, 301, 3, 'LIVRE');

-- ==============================================================
-- 5. RESERVAS — por CPF + NUMERO + ANDAR
-- ==============================================================

-- Ana → Quarto 101
INSERT INTO COCAO_RESERVA (ID_USUARIO, ID_QUARTO, DATA_CHECK_IN, DATA_CHECK_OUT, NUMERO_HOSPEDES)
SELECT h.ID_USUARIO, q.ID_QUARTO, DATE '2025-11-10', DATE '2025-11-12', 1
FROM COCAO_HOSPEDE h
JOIN COCAO_QUARTO q ON q.NUMERO = 101 AND q.ANDAR = 1
WHERE h.CPF = '11122233344';

-- Pedro → Quarto 201
INSERT INTO COCAO_RESERVA (ID_USUARIO, ID_QUARTO, DATA_CHECK_IN, DATA_CHECK_OUT, NUMERO_HOSPEDES)
SELECT h.ID_USUARIO, q.ID_QUARTO, DATE '2025-11-15', DATE '2025-11-18', 2
FROM COCAO_HOSPEDE h
JOIN COCAO_QUARTO q ON q.NUMERO = 201 AND q.ANDAR = 2
WHERE h.CPF = '55566677788';

-- Maria → Quarto 301
INSERT INTO COCAO_RESERVA (ID_USUARIO, ID_QUARTO, DATA_CHECK_IN, DATA_CHECK_OUT, NUMERO_HOSPEDES)
SELECT h.ID_USUARIO, q.ID_QUARTO, DATE '2025-11-20', DATE '2025-11-21', 2
FROM COCAO_HOSPEDE h
JOIN COCAO_QUARTO q ON q.NUMERO = 301 AND q.ANDAR = 3
WHERE h.CPF = '99988877766';

-- ==============================================================
-- 6. SERVIÇOS — por CPF + DATA_SOLICITACAO
-- ==============================================================

-- Ana: Café da manhã
INSERT INTO COCAO_HOSPEDE_SERVICO (ID_USUARIO, CODIGO_SERVICO, ID_RESERVA, DATA_SOLICITACAO, QUANTIDADE)
SELECT 
    h.ID_USUARIO, 
    0101, 
    r.ID_RESERVA, 
    DATE '2025-11-11', 
    2
FROM COCAO_HOSPEDE h
JOIN COCAO_RESERVA r ON r.ID_USUARIO = h.ID_USUARIO
WHERE h.CPF = '11122233344' 
  AND r.DATA_CHECK_IN = DATE '2025-11-10';

-- Pedro: Lavanderia
INSERT INTO COCAO_HOSPEDE_SERVICO (ID_USUARIO, CODIGO_SERVICO, ID_RESERVA, DATA_SOLICITACAO, QUANTIDADE)
SELECT 
    h.ID_USUARIO, 
    0201, 
    r.ID_RESERVA, 
    DATE '2025-11-16', 
    3
FROM COCAO_HOSPEDE h
JOIN COCAO_RESERVA r ON r.ID_USUARIO = h.ID_USUARIO
WHERE h.CPF = '55566677788' 
  AND r.DATA_CHECK_IN = DATE '2025-11-15';

-- Maria: Transfer
INSERT INTO COCAO_HOSPEDE_SERVICO (ID_USUARIO, CODIGO_SERVICO, ID_RESERVA, DATA_SOLICITACAO, QUANTIDADE)
SELECT 
    h.ID_USUARIO, 
    0302, 
    r.ID_RESERVA, 
    DATE '2025-11-20', 
    1
FROM COCAO_HOSPEDE h
JOIN COCAO_RESERVA r ON r.ID_USUARIO = h.ID_USUARIO
WHERE h.CPF = '99988877766' 
  AND r.DATA_CHECK_IN = DATE '2025-11-20';





